name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
